# Generated by Django 5.2.5 on 2025-08-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_historicalorganization_historicalsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalsubscription',
            name='renew_interval',
            field=models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renew_interval',
            field=models.CharField(choices=[('monthly', 'monthly'), ('yearly', 'yearly')], default='monthly', max_length=10),
        ),
    ]
